import type { Metadata } from "next";
import "./globals.css";
import Sidenav from "@/components/layout/sidenav";
import EventsPanel from "@/components/custom/events-panel";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Hacktock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-row w-full h-full min-h-screen">
        <Sidenav />
        <main className="flex-1 h-full overflow-auto">{children}</main>
        <EventsPanel />
        <Toaster />
      </body>
    </html>
  );
}
